"""Creacion entidades faltantes

Revision ID: 52e59ce03fe5
Revises: f613251fe101
Create Date: 2025-02-10 13:02:55.341775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e59ce03fe5'
down_revision = 'f613251fe101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulo',
    sa.Column('itemcode', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('frngname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('itemcode')
    )
    op.create_table('inventario',
    sa.Column('docnum', sa.Integer(), nullable=False),
    sa.Column('fechaInicio', sa.Date(), nullable=False),
    sa.Column('fechaFin', sa.Date(), nullable=True),
    sa.Column('almacen', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('comentarios', sa.String(length=100), nullable=True),
    sa.Column('basedatos', sa.Enum('ACABADOS', 'IDR', 'DISTRIBUIDORA', 'FRONTERA', name='basedatosenum'), nullable=False),
    sa.PrimaryKeyConstraint('docnum')
    )
    op.create_table('proveedor',
    sa.Column('proveedor_id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('proveedor_id')
    )
    op.create_table('codigo_barras',
    sa.Column('codigo_barras', sa.String(length=100), nullable=False),
    sa.Column('itemcode', sa.String(length=50), nullable=False),
    sa.Column('proveedor_id', sa.String(length=50), nullable=False),
    sa.Column('pqt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['itemcode'], ['articulo.itemcode'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.proveedor_id'], ),
    sa.PrimaryKeyConstraint('codigo_barras')
    )
    op.create_table('inventario_detalle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('docnum', sa.Integer(), nullable=False),
    sa.Column('itemcode', sa.String(length=50), nullable=False),
    sa.Column('cantidad_almacen', sa.Float(), nullable=False),
    sa.Column('cantidad_contada', sa.Float(), nullable=False),
    sa.Column('diferencias', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['docnum'], ['inventario.docnum'], ),
    sa.ForeignKeyConstraint(['itemcode'], ['articulo.itemcode'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventario_detalle')
    op.drop_table('codigo_barras')
    op.drop_table('proveedor')
    op.drop_table('inventario')
    op.drop_table('articulo')
    # ### end Alembic commands ###
